import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import AdminHeader from "~/components/AdminHeader";

import {
	ClerkProvider,
	SignInButton,
	SignUpButton,
	SignedIn,
	SignedOut,
	UserButton,
	useUser,
} from "@clerk/nextjs";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<ClerkProvider>
			<html lang="en" className={`${geist.variable}`}>
				<body>
					<header className="bg-gray-100 h-16 gap-4 p-4 text-2xl">
						<div className="container mx-auto px-4">
						<h1 className="text-2xl font-bold inline-block">Potree Viewer</h1>
						<div className="float-right">
							<SignedOut>
								<SignInButton />
							</SignedOut>
							<SignedIn>
							<AdminHeader/>
							<UserButton />
							</SignedIn>
						</div>
						</div>
					</header>
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
